//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rota()
        {
            this.Satis = new HashSet<Satis>();
        }
    
        public int Id { get; set; }
        public string Nereden { get; set; }
        public string Nereye { get; set; }
        public Nullable<System.DateTime> Eklenme_Tarih { get; set; }
        public Nullable<int> UrunId { get; set; }
    
        public virtual Urun Urun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satis> Satis { get; set; }
    }
}
