//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public int Id { get; set; }
        public Nullable<System.Guid> MusteriID { get; set; }
        public System.DateTime SatisTarihi { get; set; }
        public Nullable<int> RotaID { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Rota Rota { get; set; }
    }
}
